<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Cart Menu</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>38cacb69-ac5b-419b-8ab6-50c47e26952a</testSuiteGuid>
   <testCaseLink>
      <guid>a3a112a0-e424-43e7-8f6c-56a419b5eca7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Menu/Add To Cart</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b5f5728-39e8-46e7-81ff-cd7dc84b526b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>false</value>
         <variableId>d232173f-0ece-4960-8504-39921cf9dc04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>true</value>
         <variableId>b00c782f-1fef-47ee-a224-530c3064d448</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dcd35625-eb0d-492f-8684-932cb8337192</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Menu/Remove From Cart by Swipe</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9c7b3bf-7458-4928-9caf-4fd61a4688d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f2401b5-4262-4e4f-b8ab-f38ea70fb665</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bef5e19e-6fac-4c96-86f5-780807185b8a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a4989591-f91d-4861-ab8d-72b9f87d08f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Cart Menu/Remove From Cart by Tap</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>[&quot;Sauce Labs Onesie&quot;]</value>
         <variableId>53581714-af23-4af8-9278-fef2a70e90a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96eca668-e40c-4a73-b735-ac6099404a13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>953af30c-662f-47e3-8158-d540b50ba257</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
